name: "Helm Conftest"
description: "Write tests against your Helm Charts using Open Policy Agent"
author: "Gareth Rushgrove"
branding:
  icon: "check"
  color: "green"
inputs: 
  file:
    description: "The directory containing the Chart configuration"
    required: true
  output:
    description: "Output format for results"
    default: "stdout"
runs:
  using: 'composite'
  steps:
    - run: ls -al ${{ github.action_path }}
      shell: bash
    - run: cat $deployment_file > ${{ github.action_path }}/deployment.yaml
      env:
        deployment_file: ${{ inputs.file }}
      shell: bash
    - run: docker run --rm -v ${{ github.action_path }}:/project openpolicyagent/conftest test deployment.yaml
      shell: bash