name: "Helm Conftest"
description: "Write tests against your Helm Charts using Open Policy Agent"
author: "Gareth Rushgrove"
branding:
  icon: "check"
  color: "green"
inputs: 
  chart:
    description: "The directory containing the Chart configuration"
    required: true
  output:
    description: "Output format for results"
    default: "stdout"
runs:
  using: 'composite'
  steps:
    - run: ls -al ${{ github.action_path }}
      shell: bash
    - run: docker run --rm -v ${{ github.action_path }}:/project instrumenta/conftest-action/helm ${{ inputs.chart }}
      shell: bash